name: Create container

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      IMAGE_NAME: ne4upara/ne4upara:0.0.1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

      - name: Pull Docker image from Docker Hub
        run: docker pull ${IMAGE_NAME}

      - name: Use Docker image from Docker Hub
        run: |
          docker run -d \
            --name your-container-name \
            -e YOUR_ENV_VARIABLE=value \
            -p 8080:80 \
            ${IMAGE_NAME}

      - name: Your Additional Steps
        run: |
          
      - name: Stop and Remove the Docker container
        run: docker stop your-container-name && docker rm your-container-name
