
  name: Java CI with Maven

  on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

  jobs:
    build:
      runs-on: ubuntu-latest

      services:

        my-database:
          image: my-database-image
          ports:
            - 5432:5432

      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Docker
          uses: docker/setup-docker@v2
          with:
            dockerfile: Dockerfile

        - name: Set up JDK 20
          uses: actions/setup-java@v2
          with:
            java-version: '20'
            distribution: 'temurin'

        - name: Build and test with Maven
          run: mvn clean install

