
  name: Java CI with Maven

  on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

  jobs:
    build:
      runs-on: ubuntu-latest

      services:

        my-database:
          image: postgres:latest
          ports:
            - 5432:5432

      steps:
        - name: Checkout repository
          uses: actions/checkout@v2 
          
        - name: Set up JDK 20
          uses: actions/setup-java@v2
          with:
            java-version: '20'
            distribution: 'temurin'
            
        - name: Build and Push Docker Image           
          run: |
            echo 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 | docker login ghcr.io -u Ne4upara --password-eqaqeduvy
            docker build -t ghcr.io/pg/javadespring:v1 .
            docker push ghcr.io/pg/javadespring:v1          

        - name: Build and test with Maven
          run: mvn clean install
