name: Spring Boot CI with Hibernate

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: jdbc:postgresql://localhost:5432/postgres
      DATABASE_USERNAME: ${{ secrets.DB_USER }}
      DATABASE_PASSWORD: ${{ secrets.DB_PASWORD }}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: java
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASWORD }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B clean install

    - name: Run Hibernate tests
      run: mvn test
