name: Spring Boot CI with Hibernate

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: jdbc:h2:mem:testdb
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn -B clean install

    - name: Run Spring Boot application
      run: mvn spring-boot:run &

    - name: Wait for application to start
      run: |
        timeout=300
        while [[ ! "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8080)" == "200" ]]; do
          sleep 5
          timeout=$((timeout-5))
          if [ "$timeout" -le 0 ]; then
            echo "Application failed to start. Exiting..."
            exit 1
          fi
        done

    - name: Run Hibernate tests
      run: mvn test

    - name: Stop Spring Boot application
      run: pkill -f "java -jar"

    - name: Cleanup
      run: mvn clean
